/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_droidpop_app_Environment */

#ifndef _Included_com_droidpop_app_Environment
#define _Included_com_droidpop_app_Environment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_droidpop_app_Environment
 * Method:    nativeCheckAbi
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_droidpop_app_Environment_nativeCheckAbi
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
